### ISSUE TITLE
TypeError: chunk_batch() argument after ** must be a mapping, not NoneType

### ISSUE THREAD

**Issue by garychan22** [threestudio-project/threestudio#104]
Hi, I have tried to train dreamfusion-if but the following error was encountered.

![image](https://github.com/threestudio-project/threestudio/assets/108175311/5e8b4e08-298a-44e7-864f-e6217a853e24)

**Comment by thuliu-yt16** [comment]
Do you run it with your own prompt?

I think it's mostly because you have an empty geometry, so in validation, you get None from the geometry module. You can tweak your prompt or try with different loss lambdas, especially 
```yaml
    lambda_orient: [0, 10., 1000., 5000]
    lambda_sparsity: 1.
    lambda_opaque: 0.0
```
