### ISSUE TITLE
weird performance on prolificdreamer

### ISSUE THREAD

**Issue by Sheldonmao** [threestudio-project/threestudio#110]
Thank you for the great implementation! I am trying the demo code for prolificdreamer but getting weird performance during training. The log shows loss_z_variance quickly explodes to NaN before 100 steps and the evaluation result is blank. I wonder what might cause the problem. 

The script I am using:
```
python launch.py --config configs/prolificdreamer.yaml --train --gpu 0 system.prompt_processor.prompt="a pineapple" data.width=64 data.height=64
```

![tensorboard](https://github.com/threestudio-project/threestudio/assets/22072617/db416976-fa51-4b98-8d41-68e15a2354d3) 

<center>evaluation at 50 steps </center>

![it50-0](https://github.com/threestudio-project/threestudio/assets/22072617/fa994727-0511-43ae-ab72-545ece2cac14)

<center>evaluation at 100 steps </center>

![it100-0](https://github.com/threestudio-project/threestudio/assets/22072617/1674798a-5bb9-4c30-a5a1-21603e33be27)

I am using the commit [here](https://github.com/threestudio-project/threestudio/commit/587f6f4d619faa07545074502c2f93b2e5eee777).  Due to connection problem, I have to manually download and upload the pretrained weights for `stable-diffusion-2-1-base` and `stable-diffusion-2-1`. Will that cause the problem if the pretrained weight is not correctly assigned?

**Comment by DSaurus** [comment]
Hi,

You can use the following config and code to test your diffusion model.
```
system:
  prompt_processor_type: "stable-diffusion-prompt-processor"
  prompt_processor:
    pretrained_model_name_or_path: "stabilityai/stable-diffusion-2-1-base"
    prompt: "A cute panda"
    front_threshold: 30.
    back_threshold: 30.

  guidance_type: "stable-diffusion-vsd-guidance"
  guidance:
    pretrained_model_name_or_path: "stabilityai/stable-diffusion-2-1-base"
    pretrained_model_name_or_path_lora: "stabilityai/stable-diffusion-2-1"
    guidance_scale: 7.5
    min_step_percent: 0.02
    max_step_percent: 0.98
    max_step_percent_annealed: 0.5
    anneal_start_step: 5000
```
```
if __name__ == '__main__':
    from threestudio.utils.config import load_config
    import numpy as np
    import os
    import cv2
    cfg = load_config("configs/experimental/stablediffusion.yaml")
    guidance = threestudio.find(cfg.system.guidance_type)(cfg.system.guidance)
    prompt_processor = threestudio.find(cfg.system.prompt_processor_type)(cfg.system.prompt_processor)
    prompt_utils = prompt_processor()
    temp = torch.zeros(1).to(guidance.device)
    rgb_image = guidance.sample(prompt_utils, temp, temp, temp)
    rgb_image = (rgb_image[0].detach().cpu().clip(0, 1).numpy()*255).astype(np.uint8)[:, :, ::-1].copy()
    os.makedirs('.threestudio_cache', exist_ok=True)
    cv2.imwrite('.threestudio_cache/diffusion_image.jpg', rgb_image)
```

I can obtain the following image:
![diffusion_image](https://github.com/threestudio-project/threestudio/assets/24589363/15f2bbea-46a4-44b4-9f81-9aeb60f61ecb)
