### ISSUE TITLE
Unexpected behavior when using SequentialLR scheduler

### ISSUE THREAD

**Issue by bennyguo** [threestudio-project/threestudio#226]
Learning rate before the first milestone step is wrong. Config to reproduce:

```yaml
scheduler:
  name: SequentialLR
  interval: step
  milestones:
    - 200
    - 500
  schedulers:
    - name: ConstantLR
      args:
        factor: 1
        total_iters: 99999
    - name: ConstantLR
      args:
        factor: 0.1
        total_iters: 99999
    - name: ConstantLR
      args:
        factor: 0.5
        total_iters: 99999
```

Expected: lr -- 0.1lr -- 0.5lr
Got: 5e-4 -- 0.1lr -- 0.5lr
