### ISSUE TITLE
light remove?

### ISSUE THREAD

**Issue by Gynjn** [threestudio-project/threestudio#339]
What configuration should I edit to remove the light. I want the result with only object without any shading?

Thanks:)

**Comment by DSaurus** [comment]
Hi @Gynjn ,

I think you can set ambient_only_steps to a very large number to remove light.
```
material_type: "diffuse-with-point-light-material"
material:
  ambient_only_steps: 9999999
  albedo_activation: sigmoid
```
